#!/bin/sh

#
# A set of helper classes.
#
p_success () {
	printf "[ \033[00;32mOK\033[0m ] $1\n"
}
p_info () {
	printf "[\033[1;36m .. \033[0m] $1\n"
}
p_fail () {
	printf "[\033[0;31mFAIL\033[0m] $1\n"
}
p_help() {
	printf "[\033[0;33m ? \033[0m] $1\n"
}

#
# Conditionally print the usage guide.
#
if [ $1 = "--help" ]; then
	p_help "Usage: Change into your package directory which contains your local .git/ repository and run hook."
	exit 0
fi

#
# Or install the git-hooks if the current pwd has a .git/ dir.
#
if [ "$(ls -R 2>/dev/null -A `pwd`/.git)" ]; then
	p_info "Installing git hooks in the current working directory."

	HOOKS=("$HOME/.sitegeist-hooks/hooks/"*)
	for f in "${HOOKS[@]}"
	do
		if [ -f "`pwd`/.git/hooks/$(basename $f)" ]; then
			p_info "$(basename $f) already in place."
		else
			p_info "Linking $$(basename $f) to `pwd`/.git/hooks/..."
			ln -s ${f} `pwd`/.git/hooks/
		fi
	done

	p_success "Done."
else
	p_fail "Error: Your current directory has no '.git/' folder, please change into your root package directory and run this command again."

	exit 1
fi
