#!/bin/sh
# MIT © Sindre Sorhus - sindresorhus.com

CHANGED_FILES="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

if grep -E 'package.json|npm-shrinkwrap.json'  <<< $CHANGED_FILES
then
	eval "npm install && npm prune"
fi

if grep -E 'composer.json|composer.lock' <<< $CHANGED_FILES
then
	eval "composer update"
fi
