#!/bin/sh
# MIT © Sindre Sorhus - sindresorhus.com

CHANGED_FILES="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	if grep -E $1  <<< $CHANGED_FILES
	then
		eval "$2"
	fi
}

check_run 'package.json|npm-shrinkwrap.json' "npm install && npm prune"
check_run 'omposer.json|composer.lock' "composer update"
