#!/bin/sh

BASE_DIR="$HOME/.sitegeist-hooks"
SPECS=$BASE_DIR/tests/*.spec

#
# Runs all tests which are located in the tests/ directory.
#
for spec in $SPECS
do
	if [ -f "$spec" ]; then
		$spec
	fi
done
