#!/usr/bin/env bash

#
# Post-Merge hook
# Responsible for updating the respective dependencies if a certain
# meta file has been changed in the downstream.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
HOOK_DIR="$HOME/.sitegeist-hooks"
WORKING_DIR=$(git rev-parse --show-toplevel)
CHANGED_FILES="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
CONFIG_PATH="$WORKING_DIR/.hook.yml"

#
# Include helper utils.
#
source $HOOK_DIR/utils/stringIncludes
source $HOOK_DIR/utils/executeHookExtension
source $HOOK_DIR/utils/parseYaml

#
# Helper functions which are responsible for updating the dependencies.
#
function updateNodeDependencies() {
	p_info "Updating the NPM dependencies, this may take a while..."
	npm prune && npm install
}
function updateComposerDependencies() {
	p_info "Updating the composer dependencies, this may take a while..."
	composer install
}

#
# If a `package.json` file has been changed, execute `npm prune` and `npm install`.
#
if stringIncludes $CHANGED_FILES 'package.json'; then
	updateNodeDependencies
fi

#
# If a `composer.json` file has been changed, execute `composer install`.
#
if stringIncludes $CHANGED_FILES 'composer.json'; then
	updateComposerDependencies
fi

#
# Support for additional project specific hooks.
#
if fileExists $CONFIG_PATH; then
	eval $(parseYaml $CONFIG_PATH "CONFIG_")

	executeHookExtension "post-merge" $CONFIG_extend_post_merge $@
fi

exit 0
