#!/usr/bin/env bash

#
# Post-Merge hook
# Responsible for updating the respective dependencies if a certain
# meta file has been changed in the downstream.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
HOOK_DIR="$HOME/.sitegeist-hooks"
CHANGED_FILES="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

#
# Include helper utils.
#
source $HOOK_DIR/utils/stringIncludes

#
# Helper functions which are responsible for updating the dependencies.
#
updateNodeDependencies() {
	npm prune && npm install
}
updateComposerDependencies() {
	composer install
}

#
# If a `package.json` file has been changed, execute `npm install` and `npm prune`.
#
if stringIncludes $CHANGED_FILES 'package.json'; then
	updateNodeDependencies
fi

#
# If a `composer.json` file has been changed, execute `composer install`.
#
if stringIncludes $CHANGED_FILES 'composer.json'; then
	updateComposerDependencies
fi

#
# Note: No exit code, this should bubble up from the respective install commands.
#
