#!/usr/bin/env bash

#
# Pre-Commit hook
# Responsible for linting the changed files.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
HOOK_DIR="$HOME/.sitegeist-hooks"
WORKING_DIR=$(git rev-parse --show-toplevel)
CHANGED_JS_FILES=$(git diff --cached --name-only -- '*.js')

#
# Include helper utils.
#
source $HOOK_DIR/utils/typography

#
# Check for changes in JavaScript files, and run the configured linter against them.
#
if [ ! -z "$CHANGED_JS_FILES" ]; then
	# Check for an existing pipe instance beforehand.
	echo "Hook CLI: Found changes in JavaScript files. Linting via the local 'xo' binary..."

	if [ -f "$WORKING_DIR/node_modules/.bin/xo" ]; then
		node $WORKING_DIR/node_modules/.bin/xo $CHANGED_JS_FILES
	else
		echo "Hook CLI: No local 'xo' binary found."
	fi
fi
lintResults=$?

#
# Exit with an error code if one of the linters has found errors.
#
if [ $lintResults -ne 0 ]; then
	p_fail "Something went wrong while linting the changed files.
       Fix the errors and commit again.

       If you think the linter is not intended to throw an error exit code,
       please contact the owner of the repository."

	exit 1
fi

exit 0
