#!/usr/bin/env bash

#
# Pre-Commit hook
# Responsible for linting the changed files.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
HOOK_DIR="$HOME/.sitegeist-hooks"
WORKING_DIR=$(git rev-parse --show-toplevel)
CHANGED_JS_FILES=$(git diff --cached --name-only -- '*.js')
CHANGED_PACKAGE_JSON=$(git diff --cached --name-only -- 'package.json')
CONFIG_PATH="$WORKING_DIR/.hook.yml"

#
# Include helper utils.
#
source $HOOK_DIR/utils/typography
source $HOOK_DIR/utils/fileExists
source $HOOK_DIR/utils/executeHookExtension
source $HOOK_DIR/utils/parseYaml

#
# Check for changes in JavaScript files, and run the configured linter against them.
#
if [ ! -z "$CHANGED_JS_FILES" ]; then
	p_info "Hook CLI: Found changes in JavaScript files. Linting via the local 'xo' binary..."

	if [ -f "$WORKING_DIR/node_modules/.bin/xo" ]; then
		node $WORKING_DIR/node_modules/.bin/xo $CHANGED_JS_FILES
		lintResults=$?

		#
		# Exit with an error code if one of the linters has found errors.
		#
		if [ $lintResults -ne 0 ]; then
			p_fail "Something went wrong while linting the changed files.
		       Fix the errors and commit again.

		       If you think the linter is not intended to throw an error exit code,
		       please contact the owner of the repository."

			exit 1
		fi
	else
		p_warn "Hook CLI: No local 'xo' binary found."
	fi
fi

#
# Generate/Update the npm-shrinkwrap.json file, if a package.json file has been changed.
#
if [ ! -z "$CHANGED_PACKAGE_JSON" ]; then
	p_info "Hook CLI: Seems like you've changed a 'pacakge.json' file, creating/updating a 'npm-shrinkwrap.json' for consistent dependencies..."

	# --dev is set to include devDependencies.
	npm shrinkwrap --dev
	generateResults=$?

	# Add the generated file to the commit index.
	git add npm-shrinkwrap.json

	#
	# Exit with an error code if the npm shrinkwrap command aborted.
	#
	if [ $generateResults -ne 0 ]; then
		p_fail "Seems like something went wrong while creating the npm-shrinkwrap file.

	       If this error is thrown falsely, please open a issue at ${underline}https://github.com/sitegeist/git-hooks/issues${nounderline}."

		exit 1
	fi
fi

#
# Support for additional project specific hooks.
#
if fileExists $CONFIG_PATH; then
	eval $(parseYaml $CONFIG_PATH "CONFIG_")
	executeHookExtension "pre-commit" $CONFIG_extend_pre_commit $@
fi

exit 0
