#!/usr/bin/env bash

#
# Helper function to test a string against an array.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
beginsWithAny() {
	local e
	for e in "${@:2}"; do grep -q -E "^$e"  <<< $1 && return 0; done
	return 1
}
