#!/usr/bin/env bash

source $HOOK_DIR/utils/typography
source $HOOK_DIR/utils/fileExists
source $HOOK_DIR/utils/isFileExecutable

#
# A helper function which executes the given hook extension.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
# Arguments:
# $1 The name of the currently running hook.
# $2 The path to the file to execute.
# $3 The arguments which should be passed to the hook extension.
#
# Usage:
# executeHookExtension "post_merge" "Build/Hooks/post-merge" $@
#
function executeHookExtension() {
	if [[ ! -z "$2" ]]; then
		if fileExists $2; then
			echo "Hook CLI: Found a $1 hook extension in '$2'. Executing it now..."

			if isFileExecutable $2; then
				./$2 "$3"
				if [ $? -ne 0 ]; then
					p_fail "The $1 hook extension '$2' hasn't exited with code 0, preventing this commit.
	       If this error is thrown falsely, please contact the creator of this $1 extension."

					exit 1
				fi
			else
				echo "Hook CLI: $1 hook extension '$2' is not executable, skipping it."
			fi
		fi
	fi
}
