#!/usr/bin/env bash

#
# A helper function which tests if a file is a symbolic link.
#
# Author: Tyll Weiß <weiss@sitegeist.de>
#
# Arguments:
# $1 The filepath to check.
#
# Usage:
# if isFileSymlink "$HOME/.aliases"; then
#		echo "File '$HOME/.aliases' is a symbolic link."
# fi
#
function isFileSymlink() {
	if [ -L "$1" ]; then
		return 0
	else
		return 1
	fi
}
