#!/usr/bin/env bash

source $HOOK_DIR/utils/fileExists

#
# A function which parses a yaml file and
# stores all keys in variables which you can access later on.
#
# Author: Piotr Kuczynski <@pkuczynski>
# URL: https://gist.github.com/pkuczynski/8665367
#
# Arguments:
# $1 The filepath to the .yml file.
# $2 The prefix for the variables.
#
# Usage:
# eval $(parse_yaml config.yml "config_")
# echo $config_development_database
#
function parseYaml() {
  if fileExists $1; then
    local prefix=$2
    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
    sed -ne "s|^\($s\):|\1|" \
         -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
         -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
    awk -F$fs '{
       indent = length($1)/2;
       vname[indent] = $2;
       for (i in vname) {if (i > indent) {delete vname[i]}}
       if (length($3) > 0) {
          vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
          printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
       }
    }'
  fi
}
