#!/bin/bash

#
# Helper function which runs the second argument if any of the passed file-patterns return a result.
# MIT © Sindre Sorhus - sindresorhus.com
#
stringIncludes() {
	if grep -q -E $2  <<< $1
	then
		return 0
	else
		return 1
	fi
}
